[package]
name = "s3-browser"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
gpui-kit = { git = "https://github.com/longbridge/gpui-kit", rev = "fb26e617da3add2ce2ac92a2ccc1a64bc8343135" }
aws-config = "1"
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
smol = "2"
anyhow = "1"
